### ISSUE TITLE
registering custom Injector takes forever, how to limit to relevant models?

### ISSUE THREAD

**Issue by jchambers-crescendo** [wcm-io/io.wcm.testing.aem-mock#20]
So, I have a custom injector which I am trying to use in unit tests to instantiate my models.  I am able to successfully use my injector like this:

`context.registerInjectActivateService(FragmentInjector.class);`

However, this takes over three minutes, and when I debug with a breakpoint in the injector's `InjectAnnotationProcessor2 createAnnotationProcessor(AnnotatedElement element)` method, I see that every field from EVERY `@Model` in the entire codebase is tried to see if this injector is relevant, including the FEW that I actually need (just like happens when AEM starts up, which does take minutes, which is fine there, but not every test).

Is there a way to limit what classes are run through this process to only those that are relevant?

Thank you!  More details here:
https://stackoverflow.com/questions/76831435/aem-mocks-custom-injector-registration-takes-minutes

**Comment by stefanseifert** [comment]
registering custom models injectors should be done as early as possible in the testing lifecycle, otherwise it leads to massive re-registrations of models.

you should try to register your custom injector in `beforeSetup` instead of `afterSetup`.

**Comment by prestoncrawford** [comment]
@stefanseifert - Adding this call to the BeforeAll phase and instantiating it only once per suite is helping in my testing. I do have a related question, though. Is there a way to contain the number of models the mock AEM container tries to apply the custom injector to or is it always going to scan through all of the models. 

While putting this call in BeforeAll seems improved, it still takes hundreds of milliseconds to perform this task.

**Comment by stefanseifert** [comment]
please note that i did not speak of the junit `BeforeAll` (junit test lifecylce), but related to `beforeSetup` instead of `afterSetup` which are methods of plugins for AEM Mocks (see [ContextPlugin](https://wcm.io/testing/aem-mock/junit5/apidocs/org/apache/sling/testing/mock/osgi/context/ContextPlugin.html)), so relates to the lifecyle of plugins inside each single test execution done with the AEM mock junit extension.

making use of concepts like `BeforeAll` might by dangerous, as you risk leaking information between the tests and not have a clean setup for each test run. you can do it, but it's on your own risk.

regarding your second questions about how many models are processed by the injectors: the injectors are always applied to all registered models (with appropriated annotations). but you actually can control which/how many models are registered at all, and that is the important point performance-wise. by default, sling mocks scans the (test) classpath and registers all models classes/scans all packages found in the bundles metadata files. this is very convenient, but comes with a performance downside. you can disable this behavior by setting [registerSlingModelsFromClassPath](https://wcm.io/testing/aem-mock/junit5/apidocs/io/wcm/testing/mock/aem/junit5/AemContextBuilder.html#registerSlingModelsFromClassPath-boolean-) to false when building your AemContext object - then you have to register all models relevant for your unit test on your own - but you have full control.

**Comment by prestoncrawford** [comment]
@stefanseifert - Yeah, we tried BeforeAll, knowing leaks between tests was a risk and indeed we saw some of that behavior and abandoned it. Ultimately we found the cause of the slowdown. It wasn't the test framework or the AEM context. It was a bug in our custom injector that was slowing things down once per annotation check. Once that was fixed it ran fairly fast, actually. 

Thanks for the notes on changing the behavior of the mocks. We'll look into this. I think this issue can be closed.

**Comment by jchambers-crescendo** [comment]
For all those that come after, who find their injection registration painfully slow, we finally did find the problem, and it's admittedly pretty dumb, but I had a `log.debug(...)` in the `createAnnotationProcessor` method of the custom injector.  Just this act of writing the log slowed the process down to MINUTES, but simply removing it made speeds normal again.  Warning to all, no logging there!  🤦
